---
- import_playbook: clean-postgres.yml
- import_playbook: tune-sysctls.yml
- import_playbook: init-postgres.yml

- name: Tune Postgres for OLTP
  import_playbook: tune-postgres.yml
  vars:
    BENCHMARK: tprocc

- import_playbook: init-tprocc.yml
- import_playbook: run-tprocc.yml