# Creates a backup of a Postgres instance using parallel compression
#
# For simplicity, we also stop postgres before creating the backup. The
# instance will be restarted afterwards so we leave things the way we found
# them.
#
# Variables:
#   - db_id: Unique identifier that marks this backup.

- include_tasks: tools/stop-postgres.yml

- name: Ensure the dump directory exists
  file:
    path: ~/pgsql/dump
    state: directory

- name: Back up newly initialized benchmark contents
  shell: "tar -C ~/pgsql -cf - data | pigz > ~/pgsql/dump/{{ db_id }}.tar.gz"
  args:
    warn: false

- include_tasks: tools/start-postgres.yml
