- name: Run a checkpoint
  command: "{{ postgres_bin }}/psql -h /tmp -c 'CHECKPOINT' postgres"
  args:
    removes: ~/pgsql/data/postmaster.pid

- name: Stop PostgreSQL
  command: "{{ postgres_bin }}/pg_ctl -D ~/pgsql/data stop -m fast"
  args:
    removes: ~/pgsql/data/postmaster.pid
