# Stop pg_buffercache monitoring

- name: Stop buffer cache monitoring
  shell: |
    kill $(ps -ef | grep buffercache_monitor.sh | grep -v grep | awk '{ print $2 }')
  delegate_to: "{{ hostvars[inventory_hostname].driver if hostvars[inventory_hostname].driver is defined else omit }}"  

- name: Download buffer cache log
  fetch:
    src: "{{ buffercache_log }}"
    dest: ../results/
    flat: yes
  delegate_to: "{{ hostvars[inventory_hostname].driver if hostvars[inventory_hostname].driver is defined else omit }}"  
